### ISSUE TITLE
Backend version ?

### ISSUE THREAD

**Issue by lucas-goldner** [hack3r-0m/NFTminter#13]
I am currently trying to convert this amazing project into something I can call from the backend, so I would like to know if for example I only want to mint nfts with one certain wallet, would it be possible to not use the web3modal at all and if yes how ?

**Comment by lucas-goldner** [comment]
Ok I managed it by using truffle hd wallet provider I guess that should be fine, but I am getting an error at:
```
{
  id: 999999999999,
  jsonrpc: '2.0',
  result: undefined,
  error: {
    message: 'Error: the method eth_signTypedData_v4 does not exist/is not available\n' +
      '    at /Users/lucasgoldner/Dev/JS/Client/NFT10/node_modules/truffle-hdwallet-provider/dist/index.js:15:632675\n' +
      '    at t.i.onreadystatechange (/Users/lucasgoldner/Dev/JS/Client/NFT10/node_modules/truffle-hdwallet-provider/dist/index.js:15:748948)\n' +
      '    at t.e.dispatchEvent (/Users/lucasgoldner/Dev/JS/Client/NFT10/node_modules/truffle-hdwallet-provider/dist/index.js:1:142373)\n' +
      '    at t._setReadyState (/Users/lucasgoldner/Dev/JS/Client/NFT10/node_modules/truffle-hdwallet-provider/dist/index.js:15:753708)\n' +
      '    at t._onHttpResponseEnd (/Users/lucasgoldner/Dev/JS/Client/NFT10/node_modules/truffle-hdwallet-provider/dist/index.js:15:756793)\n' +
      '    at IncomingMessage.<anonymous> (/Users/lucasgoldner/Dev/JS/Client/NFT10/node_modules/truffle-hdwallet-provider/dist/index.js:15:756051)\n' +
      '    at IncomingMessage.emit (events.js:327:22)\n' +
      '    at endReadableNT (_stream_readable.js:1327:12)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:80:21)',
    code: -32000
  }
}
undefined
```

when running:
```
const txnhash = await web3.currentProvider.sendAsync(
    rpc,
    async function (error, response) {
      console.log(response);
      let { r, s, v } = getSignatureParameters(response.result);
 ```

Do you know a fix maybe ? the result keeps retrieving undefined as eth_signTypedData_v4 seems to be unavailable

**Comment by lucas-goldner** [comment]
Oh I see I guess I really need another provider since that truffleHDProvider does not provide eth_signTypedData_v4 t-t

**Comment by hack3r-0m** [comment]
hey @lucas-goldner that's because `executeMetaTransaction` are only allowed from the domain (https://mintnft.today) so solving for truffle HD wallet wouldn't necessarily help, for using  `executeMetaTransaction` you will need to set up your relayer or you can directly call mint function (that would cost gas)
