### ISSUE TITLE
Error: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by jarrillaga** [hack3r-0m/NFTminter#24]
@hack3r-0m I'm trying to run the Docker image but I'm getting this error when starting the backend: 

> TypeError: Cannot read property 'startsWith' of undefined
> at Accounts.privateKeyToAccount (/app/node_modules/web3-eth-accounts/lib/index.js:107:21)

Any help would be appreciated. 
Thanks for the project !!!

**Comment by QEDK** [comment]
Put this as a .env file in the directory first.
```
DB_USER=
DB_PASSWORD=
DB_URL=
DB_NAME=
PRIVATE_KEY=
```

**Comment by jarrillaga** [comment]
@QEDK I understand that I need to deploy the DB and create the variables in the .env file. 

Where can I find the database backup ?

**Comment by QEDK** [comment]
There is no backup, and it is not needed, it's only for the special 18+ NFTs - and we have a prod DB but it is private. You can use an empty DB and/or remove the code where the DB is required.

**Comment by jarrillaga** [comment]
@QEDK I'm seeing in the server.js file that 'collection' and 'addresses' are all over the code. You told me that the DB is only needed for the special 18+ NFTs but it's not trivial to remove all the DB related code. Probably I'm not understanding something, I would really appreciate if you can clarify it.

Sincerely it would be good to be able to run the solution using Docker or have a readme file with the basic steps to run it. 

Thanks again !

**Comment by QEDK** [comment]
> 
> 
> @QEDK I'm seeing in the server.js file that 'collection' and 'addresses' are all over the code. You told me that the DB is only needed for the special 18+ NFTs but it's not trivial to remove all the DB related code. Probably I'm not understanding something, I would really appreciate if you can clarify it.
> 
> Sincerely it would be good to be able to run the solution using Docker or have a readme file with the basic steps to run it.
> 
> Thanks again !

For barebones functionality, you can just remove all endpoints other than `/mint`. The collection is required for approving 18+ tokens through an admin portal, if you need that too, you can create those databases in mongoDB. Right now, we don't have the bandwidth to provide support for this any more than maintaining the hosted site so I suggest looking through the code first to understand how it works, if you want to implement the admin portal as well, I can provide the schema to you by the end of this week.

**Comment by jarrillaga** [comment]
Crystal clear ! I'll understand the code and I'll let you know in case I have any other question :) !!
